class MeglevoCsomoError(Exception):
    """Ugyanezekkel az adatokkal már létezik csomó az adatbázisban."""